return PlaceObj('ModDef', {
	'title', "MultiAim",
	'description',
	"Select correctly aiming first turret. Then add all other turrets to the selection and press Ctrl-Shift-T. Done.\nAlternatively, select multiple turret and use 'Target Areas' button, then click on target as usual.\n\nDone.\n\n[b]FEEDBACK[/b]\n[i]The Comments section is disabled and your only way to send feedback is via my [url=https://discord.gg/65CHafxND7]discord server[/url][/i]\n\n[b]SUPPORT ME![/b]\nPlease support me with as little as $1 on my [url=https://patreon.com/pardeike]Patreon page[/url]\n\n[b]CONTACT[/b]\nAndreas Pardeike\nEmail: andreas@pardeike.net\nDiscord: https://discord.gg/DsFxX5PG67\nTwitter: https://twitter.com/pardeike\nTwitch: https://twitch.tv/brrainz",
	'image', "Mod/o7FU4i/preview.png",
	'external_links', {
	"https://www.patreon.com/pardeike",
	"https://www.github.com/pardeike",
},
	'last_changes', "Adds support for using the UX and restricts to allowed position",
	'id', "o7FU4i",
	'author', "Brrainz",
	'version_major', 1,
	'version_minor', 2,
	'version', 94,
	'lua_revision', 233360,
	'saved_with_revision', 347716,
	'code', {
	"Code/Script.lua",
},
	'saved', 1705279305,
	'code_hash', -908789294768089883,
	'steam_id', "3135796716",
	'TagInterface', true,
})
